server:
  port: 9527
spring:
  application:
    name: cloud-geteway-geteway
  cloud:
    gateway:
      discovery:   #开启服务发现后才能以服务名访问
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由id
          uri: lb://CLOUD-PAYMENT-SERVICE #调用服务名 服务中心注册的
          predicates:
            - Path=/payment/get/**  #匹配路径
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.2:7002/eureka
  instance:
    instance-id: geteway9527