server:
  port: 84
spring:
  application:
    name: sentinel-consumer
  cloud:
    nacos:
      discovery:
        server-addr: a.aikele.top:8848
    sentinel:
      transport:
        dashboard: a.aikele.top:8080
        port: 8719
