server:
  port: 7001
eureka:
  instance:
    hostname: localkele1 #服务端实例的名称
  client:
    #false表示不用向注册中心注册自己
    register-with-eureka: false
    #表示自己就是注册中心，我的职责就是维护实例，不需要去检索服务
    fetch-registry: false
    service-url:
      #设置于eureka-server交互的地址
      defaultZone: http://localkele2:7002/eureka