server:
  port: 8081
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: a.aikele.top:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.aikele: debug