server:
  port: 83
spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: a.aikele.top:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'