server:
  port: 80
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.2:7002/eureka
feign:
#  hystrix:
#    enabled: true #超时时是否降级
  client:
    config:
      default: #这里就是指的所有被加载的默认FeignClient实现的服务配置都生效
        connectTimeout: 3000 #创建链接所使用的时间
        readTimeout: 3000 #读取到可用资源所使用的时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000